### ISSUE TITLE
AHRQ comorbidities mapping ICD10

### ISSUE THREAD

**Issue by pieterst** [jackwasey/icd#150] opened 2018-05-18 08:30 UTC
I am using ICD package version 3.1.2 and R version 3.5.0. I made two observations which I cannot explain. 

1.
when I perform 
>library(icd)
>df <- data.frame(id = c(1), diagnosis = c('I120'))
>datComorbidS <- comorbid_ahrq(df, hierarchy=F )

Then this patient is assigned the comorbidity 'HTNcx', but not the comorbidity 'Renal'. 

based on the mapping for Renal  I would expect Renal to be assigned as well. 
> icd10_map_ahrq$Renal

2. The mapping for HTNcx does not seem to be entirely identical to the AHRQ SAS code. 

icd10_map_ahrq$HTNcx: 
I160,I161, I169, O164, O165 appear to missing. 

I did not observe issue 1 with ICD version 2.4.1

Thx, 

Pieter

**Comment by jackwasey** [comment] 2018-05-18 15:18
Thanks for the report. This has been fixed in the development version which I am pushing out soon. The reason is that this code appears in both renal and hypertension with complications, and a recent regression omits the second appearance. With your above code, I see:
```
datComorbidS[, "Renal"]
```
```
> icd::explain("I120")
[1] "Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease"
```
Using the current master branch with:
```
devtools::install_github("jackwasey/icd")
```
should fix your problem and the CRAN version will be updated soon.

**Closed by jackwasey** 2018-05-18 15:18 UTC
