### ISSUE TITLE
Allow information about coding schemes (ICD 9/10) to icd_explain()

### ISSUE THREAD

**Issue by kamilsi** [jackwasey/icd#107] opened 2016-11-15 10:46 UTC
In my practice it is often the case I know the coding scheme (ICD 9 vs 10) of my codes and want to get explanation for a bunch of mixed-type codes. At this point there are several troubles with this:

- icd_explain messes up the ordering and length of vector of codes
- icd_explain always tries to guess the class of ICD. Only way to specify that is to cut the vector into homogeanous codes and assign a custom class 
- if icd_explain cannot decide (because of ambiguous ICD coding type) what to assign, then it returns character(0) instead of NA which causes lots of troubles later in the workflow

It would be so much easier if function icd_explain() would accept a vector of codes and simultaneously a vector of coding types / classes.

**Comment by jackwasey** [comment] 2016-11-16 13:56
I really like this idea (your second bullet), and it wouldn't be difficult to implement.

My design goals were based heavily on my own usage, so it is helpful to hear what other people are doing. Ultimately, I had to decide a consistent and 'safe' way for people to use these functions without risking ambiguity between codes.

I agree that, if you have a vector of the ICD code type, `icd_explain` could do a better job. For data frame input, an additional column could be specified; otherwise, a vector/factor of ICD type, i.e. as string representing the class.

Should this be in `icd_explain`, or a new function? I'm leaning towards the former.

Would you be interested in putting something together to solve this problem?

Regarding bullet points 1 and 3, the ordering can't remain because the hierarchy can conflict with the natural ordering of the input data. There may be special cases where the order can be preserved. `icd_explain_table` may be useful to you.

Third bullet: NULL instead of NA sounds like a bug.

**Comment by kamilsi** [comment] 2016-11-16 14:27
First of all thank you for you work, icd() makes my work a bit easier 👍 

> Should this be in icd_explain, or a new function? I'm leaning towards the former.

yes, that was my intention - additional argument for icd_explain that would set the coding scheme for each element of a vector

> Would you be interested in putting something together to solve this problem?

Unfortunately at this point I cannot offer any help...

> Regarding bullet points 1 and 3, the ordering can't remain because the hierarchy can conflict with the natural ordering of the input data. There may be special cases where the order can be preserved. icd_explain_table may be useful to you.

I was dealing with this problem by using apply() but this strips the icd codes from the "exotic" classess (to regular character) resulting in some codes having no explanation. In such cases the output of apply() becomes a list, and missing explanations are character(0) instead of NA.

**Comment by jackwasey** [comment] 2016-11-16 14:29
Would you be able to write a minimal reproducible example of the `apply` `character(0)` problem, as a new issue?

**Comment by jackwasey** [comment] 2018-05-07 22:08
I think I'm going to close this issue. I'm wary of complicating the package by including bells and whistles which do stuff R already does. In this case, given the overlap of ICD-9 and ICD-10 codes, this task is too idiosyncratic to automate for the general case. I think it is better that `explain` (a.k.a. `icd_explain` is going to work more reliably by specifically working on ICD-9 or ICD-10 codes. This is achieved by calling the S3 version, e.g. `explain.icd10` etc, or by setting the class on codes known to be ICD-9 or ICD-10.

Please open a new issue if the third point is still a problem. In version 3 of `icd`, it looks good:

``

> explain("V10")
> [1] "Personal history of malignant neoplasm"
> explain.icd10("V10")
> [1] "Pedal cycle rider injured in collision with pedestrian or animal"
> explain.icd9("V10")
> [1] "Personal history of malignant neoplasm"

Giving a warning if there is possible ambiguity gives a lot of overhead and code-complexity, and nobody has asked for this.

**Closed by jackwasey** 2018-05-07 22:08 UTC
